package.json
yarn.lock

- #2 
이슈에 적힌 사항 중에 일단은 emotion 설치만 했습니다!
추후에 해당 이슈 번호로 새 브랜치 파서 나머지 작업 할게요

chore: emotion 설치

---

.github/workflows/build-test.yml

To 내 자신
스쿼시 머지 잊지마!!!!!!!!!!!!!!!!!!!
- close #7 
PR 올리고 push 할 때, main에 push 할 때에 빌드를 해주기 때문에 빌드 과정에서 발견할 수 있는 문제가 있으면 제때에 처단할 수 있습니다
배포를 먼저 하면 배포 자동화 과정에서 검사할 수 있고 특히 배포 환경에서의 이슈를 발견할 수 있으니
이 과정 패스하고 그냥 배포를 먼저 하면 좋은데
배포를 뭐로 해야 할지 고민되는 부분이 있어서요 ..... (이따 스크럼 때? 공유하겠습니다)
그래서 일단 빌드 테스트 직접 추가합니다

chore: 빌드 테스트 workflow 추가

---

.eslintrc.json
.vscode/settings.json
package.json
yarn.lock

- close #3 
- eslint 규칙 추가
- 현재 warning으로 되어있음. error로 바꾸면 적용됨

chore: eslint-plugin-simple-import-sort 추가

---

src/components/post/api.ts
src/components/post/index.tsx
src/components/post/types.ts
src/pages/post/index.tsx

feat: 추천 리스트 조회 

---

src/api/index.ts

- close #35 
전역에서 사용할 axiosInstance를 만들었습니다
왜냐하면 헤더에 accessToken을 매번 넣어줘야 하지 않게 하려구여
그 외에도 axios 전역적으로 설정할 것이 있으면 할 수 있기 때문입니다

chore: axiosInstance 생성

---

src/styles/global.ts

- close #37 
- 잘못 설정했던 색상값 바꾸기
- 배경 색이 다른 페이지가 있을 경우 어색하지 않도록, max-width 내에서만 배경 색상 적용되도록 수정

fix: 글로벌 배경 색상 변경

---

src/components/post/api.ts

- close #64 
의미가 더 명확한 이름으로 env 변수 네이밍을 바꾸게 되어 적용해주었습니다

refactor: env 변수 네이밍 변경 적용

---

src/components/common/BattleMusicInfo/index.tsx
src/components/post/battle/api.ts
src/components/post/battle/index.tsx
src/components/post/battle/mybattleList/api.ts
src/components/post/battle/mybattleList/index.tsx
src/components/post/battle/types.ts
src/components/post/detail/api.ts
src/components/post/detail/index.tsx
src/components/post/detail/musicInfo/index.tsx
src/components/post/index.tsx
src/components/post/types.ts

- close #89 
- 추천 피드, 추천 상세 페이지, 대결 신청 페이지 type 수정 
- 각 페이지 디자인 수정

refactor: 추천 피드, 추천 상세 페이지, 대결 신청 페이지 type 수정 

---

src/components/battle/select/index.tsx
src/components/battle/voteResult/index.tsx
src/components/common/BattleMusicInfo/index.tsx
src/components/common/Genres/index.tsx
src/components/common/Header/index.tsx

- close #93 
- 대결 숏폼 디자인 수정
- genre 오류 해결
- header 코드 수정

refactor: 전체적인 디자인 및 문제 손보기

---

src/components/common/Genres/index.tsx
src/components/post/api.ts
src/components/post/create/SelectedMusic.tsx
src/components/post/create/index.tsx
src/components/post/detail/index.tsx
src/components/post/index.tsx
src/hooks/useCreatePost.ts

- 시연영상을 위해 문제되는 부분 빠르게 수정하였음
- onSuccess에 대한 문제 해결
- 글꼴 이상한 부분 문제 해결
- 글 생성 후 화면이동
- _추천 피드 작성하고 방금 작성된 피드의 상세보기로 이동해야하는데, 이동할 id를 알 수가 없음. post에 대한 응답으로 생성된 피드의 아이디로 return 와야할듯. 지금은 null이 돌아옴_
- 추천 피드 뒤집어서 최신순으로 보이도록
- all에 대한 처리가 필요함
- all이 뜨기만하고 누르면 아무것도 안나옴 clickevent 수정이 필요해보임

fix: hotfix

---

src/components/post/api.ts

- close #103 
- post에서 사용자 로그인 토큰으로 글 써지도록 수정
- 나머지 api들고 instance로 교체

feat: api 사용자 로그인데이터 사용되도록 변경

---

src/components/login/store.ts

- close #105 
- 인증 토큰 bearer로 교체

fix: 로그인 인증 토큰 수정

---

src/components/common/BottomNav/index.tsx
src/components/common/Modal/Confirm.tsx
src/components/common/Modal/Wrapper.tsx
src/components/login/AuthRequiredModal.tsx
src/components/login/store.ts
src/components/login/useAuth.ts
src/pages/_app.tsx

- close #52
- 모달 베이스(ModalWrapper) 및 컨펌 모달 구현
- 특정 기능은 인증된 사용자만 클릭할 수 있게 하는 hook 구현 (useAuth)
- useAuth hook을 이용해 인증된 사용자만 하단 네브바의 '추천' 버튼을 통해 페이지 이동하도록
로그인이 필요한 기능은 전역 어디서든 있을 수 있기 때문에 AuthRequiredModal과 관련 상태를 전역에 두었습니다.

feat: 특정 기능은 인증된 사용자만 클릭할 수 있게 하는 hook 구현 + 바텀 네브바 '추천' 버튼에 적용

---

src/components/battle/api.ts
src/components/battle/select/index.tsx
src/components/battle/temp_dummy.js
src/components/battle/types.ts
src/components/battle/voteResult/index.tsx
src/components/common/BattleMusicInfo/index.tsx
src/components/common/skeleton/AlbumPoster.tsx
src/components/post/battle/index.tsx
src/components/post/battle/mybattleList/index.tsx
src/components/post/battle/types.ts
src/components/post/types.ts
src/hooks/useVoteResult.ts

- close #108 
- close #117
- api는 나왔지만 데이터가 현재 없는 관계로 임시 데이터 삽입
- 데이터 로딩 깰끔하게 보이도록 skeleton 제작 및 애니메이션 타이밍(값) 조정
- 건너뛰기 클릭 시, 다음 데이터로 refetching 되도록 기능 추가
- 투표 시, 다음 데이터로 refetching 되도록 기능 추가
- api 필드 네이밍 수정된 것에 따라 프론트 인터페이스도 수정
-  thumbnailUrl -> albumCoverUrl
- musicName -> title
- (다른 이슈 파서 하는게 맞는데 안하면 에러나서 같이 했슴 ㅠㅠ )

featur: 대결 투표 api연결

---

public/images/play-button.svg
src/components/common/MusicPlayButton/index.tsx
src/components/post/detail/index.tsx

- close #111 
- <MusicPlayButton src={음악 url} /> 형식으로 사용하시면 될 것 같습니다.
- 현재 Play Button Icon은 설정되어있는데 Pause Button Icon은 디자인과 관련되어 있어 임의의 Icon으로 대체했습니다.

feat: 재생 버튼 공통 컴포넌트 구현

---

src/components/common/Genres/index.tsx

- close #120
- 한 번 fetch 하면 계속 캐시를 이용하도록
- state 하나 줄이기

chore: 장르 컴포넌트 최적화

---

src/components/login/store.ts

fix: axiosInstance 디폴트 헤더에 토큰 값 유지되도록

---

public/images/arrow-right.svg
src/components/common/AlbumPoster/index.tsx
src/components/common/RecommendationPost/index.tsx
src/components/mypage/ContentList.tsx
src/components/mypage/List.tsx
src/components/mypage/UserContent.tsx
src/components/mypage/UserHeader.tsx
src/components/mypage/api.ts
src/components/mypage/types.ts
src/pages/mypage/index.tsx

- close #129 
- 마이페이지 내 목록(대결, 추천) 공통 컴포넌트 List 생성
- 추천 API 연결 (`/members/posts?limit=2`)
- 대결은 공통 컴포넌트 나오는대로 추가 예정

feat: 마이페이지 내 목록 공통 컴포넌트 생성

---

src/api/index.ts
src/components/battle/api.ts
src/components/post/api.ts
src/components/post/battle/api.ts
src/components/post/battle/mybattleList/api.ts
src/components/post/detail/api.ts

- close #137 
개인적으로 API URL 상수 네이밍으로 `SERVER`는 명확하지 않은 것 같습니다~
앞으로는 쓸 일 있다면 env랑 통일하면 좋을 것 같아요!

chore: axiosInstance에 baseURL 적용

---

src/components/common/Genres/index.tsx

- close #134 
mvp 단에서 필터링을 안 하기로 한 부분이 많아서 비활성화 옵션을 추가했습니다~

chore: 장르 비활성화 옵션 추가

---

src/components/mypage/ResultCard.tsx
src/components/mypage/UserHeader.tsx
src/components/mypage/api.ts
src/components/mypage/types.ts

- close #142 
- getUserProfile API 생성 및 호출
- UserInfo, ProfileAPI 타입 생성 및 지정

feat: 마이페이지 유저 정보 API 연결

---

src/components/post/detail/api.ts

https://github.com/prgrms-web-devcourse/Team-6Jeans-Hype-FE/pull/138 에서 오타 발생하여 .. 고쳤습니다

fix: 잘못 들어간 api path 수정

---

package.json
src/components/battle/Card.tsx
src/components/battle/list/api.ts
src/components/battle/list/hooks/useGetBattles.ts
src/components/battle/list/types.ts
src/pages/battle/list.tsx
yarn.lock

- close #140
일단 빨리 올려야 해서 이따 쓰겠습니다!

feat: 배틀 리스트 get api 연결

---

src/pages/battle/list.tsx

- close #152
참고: 브랜치 명을 잘못 지었어요 .. feat -> fix

fix: 대결 리스트 페이지 > 바텀 네브바 만큼의 바텀 패딩 추가

---

src/components/battle/api.ts
src/components/common/BattleMusicInfo/index.tsx
src/components/post/battle/index.tsx

- close #159 
- 건너뛰기 while문 사용하는 방식에서 filter로 교체

fix: 건너뛰기 알고리즘 수정

---

src/components/common/BattleMusicInfo/index.tsx

refactor: 이미지 가운데 정렬 넣기

---

src/components/battle/list/api.ts
src/components/battle/list/index.tsx
src/components/mypage/battle/api.ts
src/components/mypage/battle/useGetMyBattleList.ts
src/pages/battle/list.tsx
src/pages/mypage/battle/index.tsx

- close #156 
제 아이디로 참여한 대결이 하나도 없는데 지금 음악 검색 api가 작동 안 해서 데이터를 만들 수가 없어서 테스트를 못했어요ㅠ
일단 PR 올려놓습니다 ..
=> 성현 토큰으로 확인 완료

feat: 참여한 대결 리스트 페이지 구현

---

src/components/battle/select/index.tsx
src/components/common/Genres/index.tsx
src/components/common/skeleton/AlbumPosterSkeleton.tsx
src/components/common/skeleton/GenreSkeleton.tsx
src/components/common/skeleton/MusicListSkeleton.tsx
src/components/post/SearchMusics/MusicList.tsx
src/components/post/battle/mybattleList/index.tsx
src/components/post/create/index.tsx
src/components/post/index.tsx

- close #150 
- skeleton 컴포넌트 네이밍 변경
- 로딩중인 경우 skeleton 보여주기
- 추천 글 목록
- 장르
- 추천 글 작성에서 앨범 표지

refactor: skeleton 추가

---

src/components/post/detail/index.tsx

- close #164 
- 하단 바 펼치기/접기 자연스럽게 되도록 수정
- drag로 열고 닫기도 해보려고 했는데 모바일이랑 pc랑 이벤트가 달라서 포기함

fix: PostDetailContent 개선

---

src/components/common/RecommendationPost/index.tsx
src/components/mypage/UserContent.tsx
src/components/mypage/api.ts
src/components/mypage/types.ts
src/components/post/battle/index.tsx

- close #147 
- 마이페이지 대결 목록 `/members/battles?limit=2` API 연결 완료
- 대결 신청 페이지 Header 추가 (@Park-min-hyoung 부탁)
- 대결 신청 버튼 클릭 시 대결 신청 페이지로 이동

feat: 마이페이지 대결 목록 API 연결

---

src/components/post/api.ts
src/components/post/index.tsx

refactor: 추천 피드 리팩토링

---

src/components/login/AuthRequiredPage.tsx

- close #184
이슈에서 작업 배경 확인해주세요~

fix: AuthRequiredPage replace 필요 없는 조건문 제거

---

src/components/ranking/RankingCard.tsx
src/components/ranking/api.ts
src/components/ranking/index.tsx
src/components/ranking/types.ts
src/pages/index.tsx
src/pages/ranking/index.tsx

- close #177 
- 유저 랭킹 페이지 만들기
-  /members/profile에서 내 랭킹과 닉네임 가져와서 리스트에 있다면 디자인 다르게 보이도록 함

feat: 유저 랭킹 페이지 만들기

---

src/components/mypage/ContentList.tsx

- close #173 
- 대결 목록 더보기 라우팅 `/mypage/battle`
- 대결 목록 페이지 개발까지 생각하고 이슈를 팠는데 제 파트가 아니였어요 .. 그래서 되게 간단한 이슈가 되었습니다 ㅠ
- 추천 목록과 공통 컴포넌트여서 추천 목록 페이지 생성 후 라우팅 추가 예정

feat: 대결 목록 더보기 라우팅

---

src/components/battle/api.ts
src/components/battle/select/index.tsx
src/components/battle/types.ts
src/components/battle/voteResult/index.tsx
src/components/common/BattleMusicInfo/index.tsx
src/components/common/Genres/index.tsx
src/components/common/skeleton/GenreSkeleton.tsx
src/hooks/useVoteResult.ts

- close #187
- api 구조 변경
- 누락된 타입 생성 || 수정
- 디자인 일부 교체

refactor: 대결 투표 리팩토링

---

src/components/battle/constants.ts
src/components/battle/list/api.ts
src/components/battle/list/hooks/useGetBattles.ts
src/components/battle/list/index.tsx
src/components/battle/types.ts
src/components/common/Filter.tsx
src/components/common/Genres/index.tsx
src/pages/battle/list.tsx
src/styles/reset.ts

feat: 대결 피드 페이지 status 필터링 구현

---

src/components/common/Header/index.tsx
src/components/ranking/RankingCard.tsx
src/components/ranking/index.tsx
src/styles/global.ts

- close #196 
- 디자인 수정
- 랭킹 홀수/짝수 다르게
- 호버 이벤트
- 디자인 잘못된 부분 수정

refactor: 랭킹페이지 디자인 수정

---

src/components/ranking/api.ts

feat: 랭킹 페이지 api 연동

---

src/components/common/ImageButtons/BattleButton.tsx
src/components/common/ImageButtons/LikeButton.tsx

fix: 로그인 안 한 유저 막기

---

src/components/common/Genres/index.tsx
src/components/common/Header/index.tsx
src/components/common/NoContent/index.tsx
src/components/mypage/ContentList.tsx
src/components/mypage/UserContent.tsx
src/components/post/SearchMusics/SearchInput.tsx
src/components/post/SearchMusics/index.tsx
src/components/post/battle/index.tsx
src/components/post/detail/index.tsx
src/components/ranking/RankingCard.tsx
src/pages/battle/detail/index.tsx
src/pages/battle/list.tsx
src/pages/mypage/battle/index.tsx
src/styles/global.ts

- close #172 
- 데이터가 없을 경우 사용할 `NoContent` 공통 컴포넌트 생성
- `Header` 공통 컴포넌트 스타일 통일
- 사용되는 모든 곳 체크 후 통일 완료

feat: 마이페이지 NoContent 적용

---

src/pages/battle/list.tsx

@Park-min-hyoung 이 발견해준 오류 입니다 ㅎㅎ
캐시 타임 stale 타임을 설정해놓고 매번 refetch를 하게 했던 ...

fix: 쓸모 없는 refetch 없애기

---

src/components/common/ImageButtons/BattleButton.tsx
src/components/common/RecommendationPost/index.tsx
src/components/post/index.tsx

- close #176 
- 추천 피드에서의 recommendationPost에 username 추가
- 대결신청 버튼 영역 밀리는 이슈 해결

chore: recommendationPost username 추가

---

src/components/post/battle/index.tsx
src/styles/global.ts

- close #211
- post/battle Header 스타일 수정
- global.ts `height: 100%`으로 다시 복구

fix: post/battle Header 스타일 수정

---

src/components/common/MusicPlayButton/index.tsx

- close #227 
- svg 파일 import 해서 사용

refactor: svg 파일 import 해서 사용

---

public/images/no-background-logo-white.svg
src/components/main/RandomBattle.tsx
src/pages/index.tsx

feat: 메인 페이지 뼈대 및 진행 중인 대결 영역 마크업

---

src/components/login/useAuth.ts

별거 없지만 여기저기서 recoil state에 직접 접근하는 것보다 해당 훅 거치도록 하는 게 안전할 것 같아서 추가했습니다~

chore: useAuth에 getAccessToken 추가

---

src/components/common/BottomNav.tsx
src/components/main/GenreTop10Post/index.tsx
src/components/ranking/api.ts
src/components/ranking/index.tsx
src/pages/index.tsx
src/pages/ranking/index.tsx

- close #246 
- 메인화면에 랭킹 추가
- 메인에 gerneTop10 붙이기

feat: 메인 화면 구성

---

src/components/post/api.ts

fix: 검색 문제 해결

---

src/components/battle/Detail/Battle/index.tsx
src/components/battle/Detail/BattleMusic/index.tsx
src/components/battle/voteResult/index.tsx
src/components/common/AlbumPoster/index.tsx
src/pages/battle/detail.tsx
src/pages/battle/short.tsx
src/pages/test/index.tsx

- #228 
- 대결 투표 쇼츠 페이지 코드 재구성
- 대결 투표 디테일 페이지 코드 재구성
- 페이지 변경에 따른 애니메이션 수치 조절

refactor: 대결 투표 페이지 코드 재구성

---

src/components/profile/ContentList.tsx
src/components/profile/post/api.ts
src/components/profile/post/useGetMyPostList.ts
src/pages/profile/battle/index.tsx
src/pages/profile/post.tsx

- close #264 
- 유저프로필 더보기 API 연결 완료
- `/profile/battle?memberId=${memberId}`
- `/profile/posts?memberId=${memberId}`

feat: 유저프로필 더보기 API 연결

---

src/components/profile/ContentList.tsx
src/components/profile/UserContent.tsx

- close #217 
- 리스트 없는 경우 더보기 버튼 안보이게 처리

fix: 리스트 없는 경우 더보기 버튼 안보이게 처리

---

src/components/common/Header/index.tsx
src/components/post/api.ts
src/pages/battle/list.tsx
src/pages/battle/short.tsx

fix: 뒤로가기 없애기

---

src/components/post/api.ts

fix: api 교체

---

src/components/battle/detail/Battle/index.tsx
src/pages/battle/detail.tsx
src/pages/battle/short.tsx

- close #276
음악 선택 로직은 Battle 컴포넌트의 관심사라 생각해서 옮겼습니다!

refactor: 음악 선택 로직 Battle 컴포넌트에 넣기

---

src/components/battle/detail/BattleMusic/index.tsx
src/components/common/RecommendationPost/index.tsx
src/components/post/SearchMusics/MusicList.tsx
src/components/post/battle/mybattleList/index.tsx
src/components/post/detail/index.tsx
src/pages/post/index.tsx

- close #282 
- 말줄임표 필요한 곳 추가
- `overflow-y: auto;` 필요한 곳 추가

chore: 전반적인 스타일 수정

---

src/components/battle/detail/Battle/index.tsx
src/components/battle/detail/BattleMusic/index.tsx
src/components/common/MusicPlayButton/index.tsx
src/hooks/useBattleMusicPlay.ts
src/pages/battle/short.tsx

- close #279 
- closr #289 
- play 버튼 문제 해결

refactor: play 버튼 버그 해결하기

---

src/components/login/useAuth.ts
src/components/profile/UserHeader.tsx

- close #218 
- 로그아웃 기능
- 토큰 삭제, atom state 삭제

feat: 로그아웃 기능 구현

---

src/components/battle/api.ts

- close #294 
- 장르 선택 시 건너뛸 노래 없으면 건너뛰기 안되던 것 수정

fix: 건너뛰기 수정

---

src/components/post/api.ts

- close #299 
- 가라오케 음악 안뜨게 하기

feat: 음악 리스트 블랙리스트 만들기

---

src/components/common/Header/index.tsx
src/components/common/RecommendationPost/index.tsx
src/pages/battle/list.tsx
src/pages/index.tsx
src/pages/post/index.tsx

- close #302 
- before
- after

chore: 추천 피드 스타일 수정

---

src/components/post/detail/index.tsx
src/components/post/detail/musicInfo/index.tsx

- close #304 
- before
- after

chore: post detail 스타일 수정

---

src/components/common/Header/SubmitButton.tsx
src/components/common/Header/index.tsx
src/components/common/ImageButtons/BattleButton.tsx
src/components/common/ImageButtons/LikeButton.tsx
src/components/common/MusicCard/index.tsx
src/components/common/RecommendationPost/index.tsx
src/components/common/Toggle/index.tsx
src/components/post/SearchMusics/MusicList.tsx
src/components/post/SearchMusics/SearchInput.tsx
src/components/post/SearchMusics/index.tsx
src/components/post/create/SelectedMusic.tsx
src/components/post/create/index.tsx
src/hooks/useCreatePost.ts
src/pages/post/create.tsx

- close #307 
- before
- after

chore: 추천 글쓰기 스타일 수정

---

src/components/post/battle/mybattleList/index.tsx

- close #310 
- 내 추천 목록 없을 때 NoContent 적용
- 내 추천 목록 Card 디자인 수정
- before
- after

chore: 대결 신청 페이지 스타일 수정

---

src/components/main/GenreTop10Post/DeskTopPosts.tsx
src/components/main/GenreTop10Post/MobilePosts.tsx
src/pages/index.tsx

feat: 메인 이런 곡은 어때요 추천 글 없으면 추천 글 없다고 render

---

src/components/battle/detail/BattleMusic/index.tsx
src/components/battle/detail/BattleMusic/style.ts
src/components/battle/voteResult/index.tsx

refactor: 애니메이션 재적용

---

src/components/battle/detail/Battle/Finished.tsx
src/components/battle/detail/Battle/index.tsx
src/components/battle/detail/Battle/style.ts
src/components/battle/voteResult/index.tsx
src/pages/battle/detail.tsx
src/pages/battle/short.tsx

fix: 배틀 상세 관련 레이아웃 버그 Fix

---

src/pages/index.tsx

feat: 메인 페이지 > 랜덤 배틀 컴포넌트 누르면 대결 상세 페이지로 라우팅

---

src/components/battle/detail/BattleMusic/index.tsx
src/components/battle/detail/BattleMusic/style.ts

- close #321
제목은 원래 그렇게 적용돼있었는데 실수로 다른 방법으로 수정해버려서 다시 적용하면서 가수명까지 적용했습니다

fix: BattleMusic 제목, 가수명 2줄 이상일 경우 스크롤 되도록

---

src/components/profile/UserContent.tsx
src/components/profile/battle/api.ts
src/components/profile/battle/useGetMyBattleList.ts
src/pages/profile/battle/index.tsx

feat: 참여한 대결 페이지 필터링

---

src/components/battle/detail/Battle/index.tsx

- close #338 
- battle short NoContent 위치 수정
- before
- after

chore: battle short NoContent 위치 수정

---

src/components/main/GenreTop10Post/DeskTopPosts.tsx
src/components/main/GenreTop10Post/MobilePosts.tsx
src/components/profile/UserContent.tsx

- close #340 
- main NoContent 위치 수정
- before
- after

chore: main NoContent 위치 수정

---

src/components/profile/UserHeader.tsx

- close #335 
- 유저페이지에서 로그아웃 막기
- 오타나 필요없는 코드 수정

fix: 유저페이지에서 로그아웃 막기

---

src/components/battle/detail/Battle/index.tsx

- close #279 
- 재생 아이콘 유지되는 문제 막기

fix: 정지 아이콘 refetch시 유지되는 문제 막기

---

src/components/battle/detail/Battle/index.tsx
src/components/battle/detail/Battle/style.ts
src/components/common/skeleton/AlbumPosterSkeleton.tsx

- close #332 
- 대결 투표 디자인 틀어진 부분 수정

refactor: 대결 투표 디자인 틀어진 부분 수정

---

src/pages/battle/list.tsx
src/pages/battle/short.tsx

fix: 대결 쇼츠 페이지 접근 권한 처리

---

src/components/battle/detail/Battle/style.ts

chore: 누락된 디자인 추가

---

src/components/login/api.ts
src/components/login/store.ts
src/components/login/useAuth.ts

feat: 자동 로그인 시 유효한 토큰인지 체크

---

src/components/battle/detail/Battle/index.tsx

fix: 투표 여부 판별 로직 fix

---

src/components/login/AuthRequiredPage.tsx

fix: AuthRequiredPage에 접근 시 메인 페이지로 이동하도록

---

src/pages/login.tsx

feat: 로고 클릭 시 메인 페이지로 이동하도록

---

src/components/common/BottomNav.tsx

chore: BottomNav > 로그인 안 한 상태로 마이페이지 버튼 누를 시 로그인 모달 뜨도록

---

src/pages/index.tsx

chore: 진행 중 대결 없을 때 UI 처리

---

src/pages/profile/post.tsx

- close #369 
- before
- after

fix: 내 추천 목록에 마지막 추천글 바텀 Navbar에 의해 가려있는 문제 해결

---

src/components/ranking/index.tsx

- close #370 
- before
- after

fix: 유저 랭킹페이지에 등록된 유저가 없습니다 짤리는 문제 해결

---

src/pages/login.tsx

feat: 로그인 한 경우 로그인 페이지 접근 시 메인 페이지로 보내주기

---

src/components/post/create/SelectedMusic.tsx
src/components/ranking/index.tsx

- close #374 
- nocontent 넣기
- console.log 하나 있어서 같이 지움

refactor: 랭킹에 nocontent 넣기

---

src/pages/profile/battle/index.tsx

fix: 참여한 대결 리스트 페이지에 memberId query 반영하도록

---

src/pages/index.tsx

fix: 메인 페이지 레이아웃 버그 fix

---

src/components/ranking/index.tsx

- close #379 
메인 bottom에 padding 주기

fix: 메인 bottom에 padding 주기

---

src/components/ranking/index.tsx
src/pages/index.tsx

- close #383 
- main NoContent 스타일 통일
- before
- after

chore: main NoContent 스타일 통일

---

src/components/googleTagManager/Noscript.tsx
src/components/googleTagManager/Script.tsx
src/components/googleTagManager/gtm.ts
src/pages/_app.tsx
src/pages/_document.tsx

chore: GA 측정 위해 GTM 연동

---

src/components/battle/list/index.tsx
src/components/post/detail/index.tsx
src/components/ranking/RankingCard.tsx
src/pages/index.tsx

fix: 로그인 안 한 상태에서 인증 필요한 페이지 접근 시 로그인 모달 띄워주기

---

src/components/common/Modal/Alert.tsx
src/components/common/Modal/Wrapper.tsx
src/components/common/Modal/types.tsx
src/components/login/AuthRequiredModal.tsx
src/components/post/battle/mybattleList/index.tsx
src/components/profile/UserHeader.tsx

급하게 작업해서 커밋 단위 한뭉텅이인 점 양해 부탁드립니다 .. (사실 원래 나눠서 했는데 실수로 main에 해서 그냥 reset한 거 통째로 가져와서 한번에 커밋함)
이거 원래 alert을 토스트로 바꾸겠다고 했는데, router.push 때문에 토스트가 작동 안 해서 AlertModal 만들어서 사용했습니다
서버에서 보내주는 텍스트가 안 예뻐요 ..
그래서 제가 임시로 아래처럼 바꿨습니다 (관련 커밋 [921b5f4](https://github.com/prgrms-web-devcourse/Team-6Jeans-Hype-FE/pull/388/commits/921b5f4f5b194a7112976d296116685829ae6411))

fix: window.alert 대신 AlertModal 활용하도록

---

src/pages/battle/detail.tsx
src/pages/battle/short.tsx

chore: 대결 투표 수치 조절

---

src/components/profile/UserHeader.tsx

fix: 마이페이지 > 대결권 0개일 때 처리

---

src/components/profile/ContentList.tsx
src/components/profile/UserContent.tsx
src/components/profile/api.ts
src/components/profile/likes/useGetMyLikeList.ts
src/components/profile/post/useGetMyPostList.ts
src/pages/profile/likes.tsx

- close #180 
- 마이페이지 내 좋아요 목록 추가 및 API 연결
- `limit=2`
- 내 좋아요 목록 페이지 추가 및 API 연결
- 장르 필터링 완료

feat: 마이페이지 내 좋아요 목록 추가

---

src/components/common/BottomNav.tsx
src/components/post/search/store.ts
src/pages/post/searchMusics.tsx

feat: 음악 검색 결과 유지도록 하기

---

src/components/battle/Card/style.ts
src/components/common/BattleMusicInfo.tsx
src/components/common/BottomNav.tsx
src/components/common/Filter.tsx
src/components/common/Header.tsx
src/components/common/RecommendationPost.tsx
src/components/common/button/BattleButton.tsx
src/components/common/button/LikeButton.tsx
src/components/common/button/MusicPlayButton.tsx
src/components/common/button/SubmitButton.tsx
src/components/common/modal/Alert.tsx
src/components/common/modal/Confirm.tsx
src/components/post/Detail/index.tsx
src/components/post/battle/MyBattleList/index.tsx
src/components/post/battle/SelectMusic.tsx
src/components/profile/ContentList.tsx

- close #404 
- `cursor: pointer;` 적용 안된 곳 추가 및 잘못 적용된 곳 수정

feat: cursor pointer 추가
